# Generated by Django 2.1.5 on 2019-01-24 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModelName',
            new_name='Genre',
        ),
    ]
