# Generated by Django 2.1.5 on 2019-01-25 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190125_0056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='my_field_name',
            new_name='name',
        ),
    ]
